name: yelp
channels:
  - main
  - conda-forge
dependencies:
  - bzip2=1.0.8=h01d97ff_1
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py37_0
  - cython=0.29.14=py37h0a44026_0
  - findspark=1.3.0=py_1
  - joblib=0.14.0=py_0
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcxx=9.0.0=h89e68fa_1
  - libffi=3.2.1=h6de7cb9_1006
  - libgfortran=4.0.0=2
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h4bb4525_2
  - llvm-openmp=9.0.0=h40edb58_0
  - ncurses=6.1=h0a44026_1002
  - numpy=1.17.3=py37hde6bac1_0
  - openssl=1.1.1d=h1de35cc_3
  - pandas=0.25.3=py37h4f17bb1_0
  - py4j=0.10.7=py_1
  - pyspark=2.4.4=py_0
  - python=3.7.3=h93065d6_1
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - readline=8.0=hcfe32e1_0
  - scikit-surprise=1.1.0=py37h3b54f70_1001
  - setuptools=41.6.0=py37_1
  - six=1.12.0=py37_1001
  - sqlite=3.30.1=h93121df_0
  - tk=8.6.9=h2573ce8_1003
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h1de35cc_1001
  - zlib=1.2.11=h0b31af3_1006
  - pip:
    - fastfm==0.2.11
    - pip==19.3.1
    - scikit-learn==0.22
    - scipy==1.3.3
    - xlearn==0.40a1
